spring:
  application:
    name: aiservice

  mongodb:
    uri: mongodb://localhost:27017/airecommendation
    database: airecommendation

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/